### ISSUE TITLE
Sorting does not work correctly for lists with nullable types

### ISSUE THREAD

**Issue by Tropid** [Abion47/darq#15]
It seems like sorting a list of nullable types does not work.

#### pubspec.yaml
```yaml
name: sorttest
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  darq: ^1.1.1
```

#### bin/main.dart
```dart
import 'package:darq/darq.dart';

void main() {
  final xs = <int?>[null, 1, 3, 2, null];
  print(xs.orderByDescending((x) => x));
}
```

#### Expected output:

Either `(null, null, 3, 2, 1)` or `(3, 2, 1, null, null)`.

#### Actual output:

`(null, 1, 3, 2, null)`

#### Dart version:

`Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "linux_x64"`

#### Darq version (from lockfile):

```
darq:
    dependency: "direct main"
    description:
      name: darq
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
```
